spring.application.name=casaempeno


# 1. Base de Datos: 'spring' (nombre que estás usando en pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/casa_empeno

# 2. Usuario: 'postgres' (el dueño/owner de la BD en pgAdmin)
spring.datasource.username=postgres

# 3. Contraseña: 'Alejandro' (la que nos indicaste)
spring.datasource.password=Alejandro

# El resto de la configuración se mantiene:
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
server.port=8080

