--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2026-02-24 22:23:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 24807)
-- Name: articulos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.articulos (
    id bigint NOT NULL,
    estado character varying(255),
    fecha_empeno character varying(255),
    id_cliente bigint,
    tipo_articulo character varying(255),
    valor_estimado double precision
);


ALTER TABLE public.articulos OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24806)
-- Name: articulos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.articulos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articulos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 24815)
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    contrasena character varying(255) NOT NULL,
    correo character varying(255) NOT NULL,
    estado_financiero character varying(255),
    nombre_completo character varying(255) NOT NULL,
    telefono character varying(255)
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24814)
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24823)
-- Name: deudas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deudas (
    id bigint NOT NULL,
    estado character varying(255),
    fecha_pago character varying(255),
    id_articulo bigint,
    id_cliente bigint,
    monto double precision
);


ALTER TABLE public.deudas OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24822)
-- Name: deudas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deudas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deudas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4906 (class 0 OID 24807)
-- Dependencies: 218
-- Data for Name: articulos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.articulos (id, estado, fecha_empeno, id_cliente, tipo_articulo, valor_estimado) FROM stdin;
1	En empeño	2025-12-09	2	Laptop	18000
2	Empenado	2025-12-09	2	Telefono	15800
3	fhhre	2025-12-09	2	dhee	500
4	empeñado	2025-12-09	4	Laptop	3000
5	empeñado	2025-12-09	4	carro	5000
6	empenado	2025-12-09	4	bici	10000
7	empenado	2025-12-09	4	Telefono	50000
8	empenado	2025-12-10	6	xbox	6500
9	empenado	2025-12-10	6	laptop	1200
\.


--
-- TOC entry 4908 (class 0 OID 24815)
-- Dependencies: 220
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clientes (id, contrasena, correo, estado_financiero, nombre_completo, telefono) FROM stdin;
1	$2a$10$8c9R5Yf2G1s0aYh3n1e9Ye0kVb5F0zKp3nGzM1M8eV4xX5PqLxQy	juan.perez@email.com	activo	Juan Pérez	5551234567
4	$2a$10$T6ZUJd.l7unjY0kSaoUyf.Q1ISM3iCkwBvU.vL/SymkJ6ewIP.any	eduardo@gmail.com	activo	educado flores	2461756788
6	$2a$10$fttL4rp.0cPbNxLg1HleTuckOAonnq0XOrP5C4xAlVaYt5Rdbjb3a	tkadic24@gmail.com	activo	TKA24	2411875863
8	$2a$10$WjdxK8qufKR485Vsc7g42Oix9VppQUui/5Gln1Q4l4NDO7qnCwsHO	karenlopez@gmail.com	activo	Karen Lopez	2463658989
\.


--
-- TOC entry 4910 (class 0 OID 24823)
-- Dependencies: 222
-- Data for Name: deudas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deudas (id, estado, fecha_pago, id_articulo, id_cliente, monto) FROM stdin;
\.


--
-- TOC entry 4916 (class 0 OID 0)
-- Dependencies: 217
-- Name: articulos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.articulos_id_seq', 9, true);


--
-- TOC entry 4917 (class 0 OID 0)
-- Dependencies: 219
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_id_seq', 8, true);


--
-- TOC entry 4918 (class 0 OID 0)
-- Dependencies: 221
-- Name: deudas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deudas_id_seq', 1, false);


--
-- TOC entry 4753 (class 2606 OID 24813)
-- Name: articulos articulos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.articulos
    ADD CONSTRAINT articulos_pkey PRIMARY KEY (id);


--
-- TOC entry 4755 (class 2606 OID 24821)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- TOC entry 4759 (class 2606 OID 24829)
-- Name: deudas deudas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deudas
    ADD CONSTRAINT deudas_pkey PRIMARY KEY (id);


--
-- TOC entry 4757 (class 2606 OID 24831)
-- Name: clientes uk8duxx4vm6d736wokeq3u5skw7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT uk8duxx4vm6d736wokeq3u5skw7 UNIQUE (correo);


-- Completed on 2026-02-24 22:23:39

--
-- PostgreSQL database dump complete
--

